### ISSUE TITLE
Broken py 2.7 package

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda-forge/pysal-feedstock#8]
When just install pysal into a clean python 2.7 environment, the package does not import:

```
joris@joris-XPS-13-9350:~/scipy/geopandas$ conda create -n test_py27_pysal python=2 pysal
Solving environment: done

## Package Plan ##

  environment location: /home/joris/miniconda3/envs/test_py27_pysal

  added / updated specs: 
    - pysal
    - python=2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pysal-1.14.2               |             py_0        14.4 MB  conda-forge
    numpy-1.13.1               |           py27_0         6.8 MB
    python-2.7.13              |                1        13.8 MB  conda-forge
    scipy-0.19.1               |      np113py27_0        35.2 MB
    ------------------------------------------------------------
                                           Total:        70.2 MB

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.7.27.1-0      conda-forge
    libgfortran:     3.0.0-1                       
    mkl:             2017.0.3-0                    
    ncurses:         5.9-10             conda-forge
    numpy:           1.13.1-py27_0                 
    openssl:         1.0.2l-0           conda-forge
    pysal:           1.14.2-py_0        conda-forge
    python:          2.7.13-1           conda-forge
    readline:        6.2-0              conda-forge
    scipy:           0.19.1-np113py27_0            
    sqlite:          3.13.0-1           conda-forge
    tk:              8.5.19-2           conda-forge
    zlib:            1.2.11-0           conda-forge

Proceed ([y]/n)? 


Downloading and Extracting Packages
...

joris@joris-XPS-13-9350:~/scipy/geopandas$ act test_py27_pysal
(test_py27_pysal) joris@joris-XPS-13-9350:~/scipy/geopandas$ python
Python 2.7.13 | packaged by conda-forge | (default, May  2 2017, 12:48:11) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysal as ps
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joris/miniconda3/envs/test_py27_pysal/lib/python2.7/site-packages/pysal/__init__.py", line 40, in <module>
    import pysal.cg
  File "/home/joris/miniconda3/envs/test_py27_pysal/lib/python2.7/site-packages/pysal/cg/__init__.py", line 4, in <module>
    from .shapes import *
  File "/home/joris/miniconda3/envs/test_py27_pysal/lib/python2.7/site-packages/pysal/cg/shapes.py", line 1972, in <module>
    from . import standalone  # moving this to top breaks unit tests !
  File "/home/joris/miniconda3/envs/test_py27_pysal/lib/python2.7/site-packages/pysal/cg/standalone.py", line 15, in <module>
    from pysal.common import *
  File "/home/joris/miniconda3/envs/test_py27_pysal/lib/python2.7/site-packages/pysal/common.py", line 30, in <module>
    from pysal.core.FileIO import FileIO as popen
  File "/home/joris/miniconda3/envs/test_py27_pysal/lib/python2.7/site-packages/pysal/core/__init__.py", line 1, in <module>
    from . import FileIO
  File "/home/joris/miniconda3/envs/test_py27_pysal/lib/python2.7/site-packages/pysal/core/FileIO.py", line 37
    class FileIO(object, metaclass=FileIO_MetaCls):  # should be a type?
                                  ^
SyntaxError: invalid syntax
```

**Comment by jorisvandenbossche** [comment]
It seems the package was switched to a `noarch` package, but I assume it is not truly py2/3 compatible from a single source: https://github.com/pysal/pysal/blob/master/setup.py#L6

**Comment by ocefpaf** [comment]
That is probably it . I'll fix it tomorrow morning  (away from the laptop.)

**Comment by ocefpaf** [comment]
It is a pity that the code uses `build_py_2to3` :unamused: 
If I find some time I'll try a PR to change that, for now I reverted the `noarch` in #9

**Comment by jorisvandenbossche** [comment]
> It is a pity that the code uses build_py_2to3 :unamused:

yep, agree

Thanks for fixing!

**Comment by ocefpaf** [comment]
@jorisvandenbossche and @fmaussion I just merged #9 and the packages should be available soon.
You get the chance to test them please let me know if that fixed it for you.

**Comment by fmaussion** [comment]
All green!  https://readthedocs.org/projects/oggm/builds/6062913/

Thanks @ocefpaf so fast and helpful as always.

**Comment by ocefpaf** [comment]
Thanks for the feedback! It was my bad to use `noarch` without inspecting the `setup.py` file in the first place. (The eagerness to save CI time made me careless :grimacing:)
